# Generated by Django 3.2.9 on 2022-05-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapping', '0003_resorts_rating'),
        ('ski_user_experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformationmodel',
            name='resort_choice',
            field=models.ManyToManyField(blank=True, null=True, to='webscrapping.Resorts'),
        ),
    ]
