# Generated by Django 3.2.9 on 2022-05-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_user_experience', '0002_additionalinformationmodel_resort_choice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additionalinformationmodel',
            table='ski_user_experience_AdditionalInformationModel_resort_choice',
        ),
    ]
