# Generated by Django 3.2.9 on 2022-05-03 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ski_user_experience', '0003_alter_additionalinformationmodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='additionalinformationmodel',
            table=None,
        ),
    ]
