# Generated by Django 3.2.9 on 2022-05-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapping', '0003_resorts_rating'),
        ('ski_user_experience', '0004_alter_additionalinformationmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformationmodel',
            name='resort_choice',
            field=models.ManyToManyField(blank=True, null=True, related_name='resorts_list', to='webscrapping.Resorts'),
        ),
    ]
