# Generated by Django 3.2.9 on 2022-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ski_user_experience', '0005_alter_additionalinformationmodel_resort_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinformationmodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
