# Generated by Django 3.2.9 on 2022-03-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resorts',
            name='people_mover',
        ),
    ]
