# Generated by Django 3.2.9 on 2022-05-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapping', '0003_resorts_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resorts',
            name='aerial_tramway',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='chairlift',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='circulating_ropeway_gondola_lift',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='cog_railway',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='combined_installation_gondola_chair',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='funicular',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='moving_carpet',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='rope_tow_baby_lift',
        ),
        migrations.RemoveField(
            model_name='resorts',
            name='tbar_lift',
        ),
        migrations.AddField(
            model_name='resorts',
            name='resort_lift_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
