# Generated by Django 3.2.9 on 2022-05-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapping', '0005_resorts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resorts',
            name='image',
        ),
    ]
