# Generated by Django 3.2.9 on 2022-03-28 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0006_alter_companies_company_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='company_type',
            new_name='resort_type',
        ),
    ]
