# Generated by Django 3.2.9 on 2022-03-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie1', '0002_location_active'),
        ('aplicatie2', '0007_rename_company_type_companies_resort_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Resorts',
        ),
    ]
