# Generated by Django 3.2.9 on 2022-03-28 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0008_rename_companies_resorts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resorts',
            name='website',
        ),
    ]
