# Generated by Django 3.2.9 on 2022-03-31 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('aplicatie2', '0009_remove_resorts_website'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
