# Generated by Django 3.2.9 on 2022-04-04 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0010_delete_userextend'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pontaj',
        ),
    ]
