# Generated by Django 3.2.9 on 2022-04-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='assumed_technical_ski_level',
            field=models.CharField(choices=[('Beginner', 'BEGINNER'), ('Intermediate', 'INTERMEDIATE'), ('Expert', 'EXPERT')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money_to_spend',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='years_of_experience',
            field=models.IntegerField(blank=True),
        ),
    ]
