# Generated by Django 3.2.9 on 2022-04-05 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0015_auto_20220405_1601'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
