# Generated by Django 3.2.9 on 2022-04-11 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0017_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
