# Generated by Django 3.2.9 on 2022-04-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie2', '0018_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resorts',
        ),
    ]
